---
title: "HIV Treatment Cascade - Data Visualization"
author: "Brittany Bowman"
date: "10/8/2019"
output: html_document
runtime: shiny
---

This file provides a script for visualizing the HIV treatment cascade data from UNAIDS from 2015-2018 related to progress towards the 90-90-90 targets.
```{r setup, include=FALSE echo = FALSE}
# load necessary packages
library(tidyverse)
library(shiny)
library(plotly)
library(scales)
library(ggthemes)
library(RColorBrewer)
library(grDevices)
library(plotlyGeoAssets)
library(maptools)
library(sf)
library(rworldmap)
library(cleangeo)

# get working directory
getwd()

# load tidy datasets (g = global datasets, c = country datasets)
full_cascade_g <- read_rds("data/tidy_data/full_cascade_global_tidy")
full_cascade_c <- read_rds("data/tidy_data/full_cascade_country_tidy")

know_status_g <- read_rds("data/tidy_data/know_status_all_global_tidy")
know_status_c <- read_rds("data/tidy_data/know_status_all_country_tidy")

on_art_g <- read_rds("data/tidy_data/on_art_all_global_tidy")
on_art_c <- read_rds("data/tidy_data/on_art_all_country_tidy")

vl_suppress_g <- read_rds("data/tidy_data/vl_suppress_all_global_tidy")
vl_suppress_c <- read_rds("data/tidy_data/vl_suppress_all_country_tidy")

hiv_ep_g <- read_rds("data/tidy_data/tidy_hiv_ep_g")
hiv_ep_c <- read_rds("data/tidy_data/tidy_hiv_ep_c")
hiv_tx_g <- read_rds("data/tidy_data/tidy_hiv_tx_g")
hiv_tx_c <- read_rds("data/tidy_data/tidy_hiv_tx_c")

setwd("plots/")
```


```{r}
# define color palette (RBrewerPal palette Set1 with black inserted for global)
custom_palette <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#000000", "#FF7F00", "#FFFF33", "#A65628", "#F781BF")
diverge_palette <- c("#35B779FF", "#31688EFF", "#440154FF")

# define custom theme
custom_theme <- theme_tufte() +
                theme(text = element_text(family = "Helvetica"),
                      plot.title = element_text(face = "bold", size = 14, color = "black"),
                      plot.title.position = "plot",
                      plot.subtitle = element_text(margin = margin(b = 16), size = 10),
                      plot.caption = element_text(hjust = 0, margin = margin(t = 10)),
                      plot.caption.position = "plot",
                      axis.line.x = element_line(colour = "grey20", size = 0.25, linetype = "solid"), 
                      axis.line.y = element_line(colour = "grey20", size = 0.25, linetype = "solid"),
                      axis.text = element_text(size = 10),
                      legend.title = element_blank(),
                      legend.text = element_text(size = 10))

theme_set(custom_theme)
```


```{r}
# plot of percent of people living with HIV who know their status
know_status_g %>% 
  ggplot(aes(x = year, y = estimate, color = Region, group = rev(Region))) + 
  geom_point(alpha = 0.75) + 
  geom_line(alpha = 0.75) +
  geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) + 
  scale_color_manual(values = custom_palette) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 10)) +
  scale_x_discrete(expand = expansion(add = 0.1)) +
  labs(x = NULL, y = NULL, 
       title = "Percent of people living with HIV who know their status by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  annotate("text", x = 3.3, y = 92, 
           label = "paste(bold(\"UNAIDS target:\"), \" 90% of people living with HIV know their status by 2020\")", 
           parse = TRUE, size = 3.2, color = "grey20") +
  annotate("curve", x = 4, xend = 4.05, y = 92, yend = 90.3, 
           curvature = -0.9, angle = 90,
           arrow = arrow(length = unit(0.01, "npc")),
           color = "grey20")
```


```{r}
# plot of percent of people who know their HIV-positive status who are accessing treatment
full_cascade_g %>% 
  filter(measure_type == "know_status_on_art", age == "all") %>%
  ggplot(aes(x = year, y = estimate, color = Region, group = rev(Region))) + 
  geom_point(alpha = 0.75) + 
  geom_line(alpha = 0.75) +
  geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) + 
  scale_color_manual(values = custom_palette) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 8)) +
  scale_x_discrete(expand = expansion(add = 0.1)) +
  labs(x = NULL, y = NULL, 
       title = "Percent of people who know their HIV-positive status who are on ART by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  annotate("text", x = 3.1, y = 92, 
           label = "paste(bold(\"UNAIDS target:\"), \" 90% of people who know their HIV-positive status access treatment by 2020\")", 
           parse = TRUE, size = 3.2, color = "grey20") +
  annotate("curve", x = 4, xend = 4.05, y = 92, yend = 90.3, 
           curvature = -0.9, angle = 90,
           arrow = arrow(length = unit(0.01, "npc")),
           color = "grey20")
```


```{r}
# plot of percent of people on ART who achieve viral suppression
full_cascade_g %>% 
  filter(measure_type == "on_art_vl_suppress", age == "all") %>%
  ggplot(aes(x = year, y = estimate, color = Region, group = rev(Region))) + 
  geom_point(alpha = 0.75) + 
  geom_line(alpha = 0.75) +
  geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) + 
  scale_color_manual(values = custom_palette) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 8)) +
  scale_x_discrete(expand = expansion(add = 0.1)) +
  labs(x = NULL, y = NULL, 
       title = "Percent of people on ART who achieve viral suppression by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  annotate("text", x = 3.2, y = 92, 
           label = "paste(bold(\"UNAIDS target:\"), \" 90% of people on treatment have suppressed viral loads by 2020\")", 
           parse = TRUE, size = 3.2, color = "grey20") +
  annotate("curve", x = 4, xend = 4.05, y = 92, yend = 90.3, 
           curvature = -0.9, angle = 90,
           arrow = arrow(length = unit(0.01, "npc")),
           color = "grey20")
```


```{r}
# plot of progress towards 90-90-90 faceted by region
full_cascade_g %>% 
  filter(measure_type %in% c("know_status", "know_status_on_art", "on_art_vl_suppress"), 
         age == "all", year == "2018") %>%
  ggplot(aes(x = factor(measure_type, ordered = is.ordered(c("know_status", "know_status_on_art", "on_art_vl_suppress"))), 
                        y = estimate, color = Region, group = rev(Region))) + 
  geom_point() +
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci)) +
  geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) + 
  facet_wrap(~ Region, nrow = 3) +
  scale_color_manual(values = custom_palette, guide = FALSE) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 10)) +
  scale_x_discrete(expand = expansion(add = 0.25),
                   labels = c("People living with\n HIV who know\n their status",
                              "People who know\n their status\n who are on ART",
                              "People on ART\n who acheive\n viral suppression")) +
  labs(x = NULL, y = NULL, 
       title = "Progress towards 90-90-90 targets by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  theme(axis.text.x = element_text(size = 8),
        panel.spacing.x = unit(40, units = "pt"))
```


```{r}
# plot of overall progress towards each goal as a percent of total people living with HIV
full_cascade_g %>% 
  filter(measure_type %in% c("know_status", "hiv_on_art", "hiv_vl_suppress"), 
         age == "all", year == "2018") %>%
  ggplot(aes(x = factor(measure_type, ordered = is.ordered(c("know_status", "hiv_on_art", "hiv_vl_suppress"))), 
                        y = estimate, color = Region, group = rev(Region))) + 
  geom_point() +
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci)) +
  facet_wrap(~ Region, nrow = 3) +
  scale_color_manual(values = custom_palette, guide = FALSE) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 10)) +
  scale_x_discrete(expand = expansion(add = 0.25),
                   labels = c("People living with HIV\n who know their status",
                              "People living with HIV\n who are on ART",
                              "People living with HIV\n who acheive viral suppression")) +
  labs(x = NULL, y = NULL, 
       title = "Percent of all people living with HIV reaching each target by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  theme(axis.text.x = element_text(size = 8),
        panel.spacing.x = unit(40, units = "pt"))
```


```{r}
# plot of people living with HIV who know their status ordered by region for 2018
full_cascade_g %>% 
  filter(measure_type == "know_status", age == "all", year == "2018") %>%
  ggplot(aes(x = reorder(Region, estimate), y = estimate, group = rev(Region),
             color = Region == "Global")) + 
  geom_point() +
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci)) +
  geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) +
  scale_color_manual(values = c("black", "firebrick3"), guide = FALSE) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 10)) +
  coord_flip() +
  labs(x = NULL, y = NULL, 
       title = "Percent of people living with HIV who know their status, ordered by region, 2018",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  theme(axis.text.x = element_text(size = 8),
        panel.spacing.x = unit(40, units = "pt")) +
  annotate("text", x = 9.5, y = 70, 
           label = "paste(bold(\"UNAIDS target:\"), \" 90% of people living with HIV know their status by 2020\")", 
           parse = TRUE, size = 3.2, color = "grey20") +
  annotate("curve", x = 9.5, xend = 9.3, y = 87.2, yend = 89.5, 
           curvature = -0.4, angle = 90,
           arrow = arrow(length = unit(0.01, "npc")),
           color = "grey20")
```


```{r}
# plot of people who know their status who are on ART ordered by region for 2018
full_cascade_g %>% 
  filter(measure_type == "know_status_on_art", age == "all", year == "2018") %>%
  ggplot(aes(x = reorder(Region, estimate), y = estimate, group = rev(Region),
             color = Region == "Global")) + 
  geom_point() +
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci)) +
  geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) +
  scale_color_manual(values = c("black", "firebrick3"), guide = FALSE) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 10)) +
  coord_flip() +
  labs(x = NULL, y = NULL, 
       title = "Percent of people who know their HIV-positive status who are on ART, ordered by region, 2018",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  theme(axis.text.x = element_text(size = 8),
        panel.spacing.x = unit(40, units = "pt")) +
  annotate("text", x = 9.5, y = 70, 
           label = "paste(bold(\"UNAIDS target:\"), \" 90% of people who know their HIV-positive status access treatment by 2020\")", 
           parse = TRUE, size = 3.2, color = "grey20") +
  annotate("curve", x = 9.5, xend = 9.3, y = 87.2, yend = 89.5, 
           curvature = -0.4, angle = 90,
           arrow = arrow(length = unit(0.01, "npc")),
           color = "grey20")
```


```{r}
# plot of people who are on ART who are virally suppressed, ordered by region for 2018
full_cascade_g %>% 
  filter(measure_type == "know_status_on_art", age == "all", year == "2018") %>%
  ggplot(aes(x = reorder(Region, estimate), y = estimate, group = rev(Region),
             color = Region == "Global")) + 
  geom_point() +
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci)) +
  geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) +
  scale_color_manual(values = c("black", "firebrick3"), guide = FALSE) +
  scale_y_continuous(labels = percent_format(scale = 1),
                     breaks = pretty_breaks(n = 10), 
                     expand = expansion(add = 10)) +
  coord_flip() +
  labs(x = NULL, y = NULL, 
       title = "Percent of people on ART who are virally suppressed, ordered by region, 2018",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019") +
  theme(axis.text.x = element_text(size = 8),
        panel.spacing.x = unit(40, units = "pt")) +
  annotate("text", x = 9.5, y = 72, 
           label = "paste(bold(\"UNAIDS target:\"), \" 90% of people on treatment have suppressed viral loads by 2020\")", 
           parse = TRUE, size = 3.2, color = "grey20") +
  annotate("curve", x = 9.5, xend = 9.3, y = 87.2, yend = 89.5, 
           curvature = -0.4, angle = 90,
           arrow = arrow(length = unit(0.01, "npc")),
           color = "grey20")
```

```{r}
# plot of people living with HIV who know their status ordered by country for 2018

# full_cascade_c %>%
#   filter(measure_type == "know_status", age == "all", year == "2018") %>%
#   filter(!is.na(estimate)) %>%
#   ggplot(aes(x = reorder(Country, estimate), y = estimate, group = rev(Country),
#              color = Country == "Global")) +
#   geom_point() +
#   geom_linerange(aes(ymin = lower_ci, ymax = upper_ci)) +
#   geom_hline(yintercept = 90, alpha = 0.75, linetype = 3) +
#   scale_color_manual(values = c("black", "firebrick3"), guide = FALSE) +
#   scale_y_continuous(labels = percent_format(scale = 1),
#                      breaks = pretty_breaks(n = 10),
#                      expand = expansion(add = 5)) +
#   scale_x_discrete(expand = expansion(add = 1)) +
#   coord_flip() +
#   labs(x = NULL, y = NULL,
#        title = "Percent of people living with HIV who know their status, ordered by region, 2018",
#        subtitle = "Figure based on modeled estimates from UNAIDS for all ages. Countries with missing data have been removed.",
#        caption = "Source: UNAIDS special analysis, 2019") +
#   theme(axis.text = element_text(size = 8),
#         panel.spacing.x = unit(40, units = "pt"),
#         axis.ticks) +
#   annotate("text", x = 5, y = 70,
#            label = "paste(bold(\"UNAIDS target:\"), \" 90% of people living with HIV know their status by 2020\")",
#            parse = TRUE, size = 3.2, color = "grey20") +
#   annotate("curve", x = 5, xend = 4.8, y = 87.2, yend = 89.5,
#            curvature = -0.4, angle = 90,
#            arrow = arrow(length = unit(0.01, "npc")),
#            color = "grey20")
```

Prepare data for making choropleth maps.
```{r}
# manipulate country plot to calculate difference between men and women
mf_plot_data_c <- full_cascade_c %>%
  select(-lower_ci, -upper_ci) %>%
  spread(sex, estimate) %>%
  filter(age == "adult") %>%
  select(-all) %>%
  mutate(diff_f_m = female - male,
         diff_valence = as.factor(ifelse(diff_f_m < 0,-1,
                                  ifelse(diff_f_m == 0, 0, 1)))) %>%
  filter(!is.na(diff_f_m))

# unique country names in UNAIDS data
countries_unaids <- unique(full_cascade_c$Country)

# unique countries in plotly-compatible dataset
countries_plotly <- countriesCoarse$ADMIN

# find set difference between UNAIDS and plotly-compatible data
unaids_not_plotly <- setdiff(countries_unaids, countries_plotly)
plotly_not_unaids <- setdiff(countries_plotly, countries_unaids)
unaids_not_plotly
plotly_not_unaids

# recode country names to make mf_plot_data_c compatible with plotly mapping functions
mf_plot_data_c <- mf_plot_data_c %>%
  mutate(name = Country,
         name = recode(name,
                       "Bahamas" = "The Bahamas",
                       "Bolivia (Plurinational State of)" = "Bolivia",
                       "Brunei Darussalam" = "Brunei",
                       "Cabo Verde"  = "Cape Verde",
                       "Congo" = "Republic of the Congo",
                       "Côte d'Ivoire" = "Ivory Coast",
                       "Czechia" = "Czech Rep.",
                       "Democratic People's Republic of Korea" = "North Korea",
                       "Eswatini" = "Swaziland",
                       "Guinea-Bissau" = "Guinea Bissau",
                       "Iran (Islamic Republic of)" = "Iran",
                       "Lao People's Democratic Republic" = "Laos",
                       "North Macedonia" = "Macedonia",
                       "Republic of Korea" = "South Korea",
                       "Republic of Moldova" = "Moldova",
                       "Russian Federation" = "Russia", 
                       "Serbia" = "Republic of Serbia",
                       "Syrian Arab Republic" = "Syria",
                       "Timor-Leste" = "East Timor",
                       "United States" = "United States of America",
                       "Venezuela (Bolivarian Republic of)" = "Venezuela",
                       "Viet Nam" = "Vietnam"))

# define %notin% operator
'%notin%' <- Negate('%in%')

# drop some territories from world map
countriesCoarse_trimmed <- countriesCoarse[countriesCoarse@data$TYPE != "Indeterminate" & 
                                           countriesCoarse@data$TYPE != "Dependency" & 
                                           countriesCoarse@data$ADMIN %notin% 
                                              c("Aruba", "Aland", "Curacao", "Guernsey", 
                                                "Isle of Man", "Jersey", "Sint Maarten", 
                                                "Federated States of Micronesia", "Marshall Islands"), ]

# clean countriesCoarse_trimmed file
mf_geo <- clgeo_Clean(countriesCoarse_trimmed)
mf_geo <- st_as_sf(mf_geo)

# add data from mf_plot_data_c to countriesCoarse_trimmed
mf_geo <- mf_geo %>%
  left_join(mf_plot_data_c, by = c("ADMIN" = "name"))

# clean new geo file and convert to sf
mf_geo <- clgeo_Clean(countriesCoarse_trimmed)
mf_geo <- st_as_sf(mf_geo)

# join trimmed countries to mf_plot_data_c
mf_plot_data_c <- mf_plot_data_c %>%
  right_join(select(countriesCoarse_trimmed@data, name = ADMIN, code = ISO3), by = "name")
```


Make interactive choropleth maps for each metric
```{r}
# alternative plot with individual trace for each country
# plot_ly(
#    filter(mf_geo, year == "2018", measure_type == "know_status"), 
#    split = ~code,
#    color = ~diff_f_m,
#    alpha = 1,
#    showlegend = FALSE
#     )

# specify light grey boundaries
l <- list(color = toRGB("grey20"), width = 0.5)

# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  landcolor = toRGB("white"),
  showland = TRUE,
  showcountries = TRUE,
  countrycolor = toRGB("grey70"),
  countrywidth = 0.5,
  projection = list(type = 'Mercator')
  )

# plot choropleth of difference between percent of women and men who know their HIV status 
mf_plot_data_c %>%
  filter(year == "2018", measure_type == "know_status") %>%
  plot_geo(offline = TRUE) %>%
  add_trace(
    type = "choropleth", 
    z = ~diff_f_m, color = ~diff_f_m, colors = "PuOr",
    text = ~Country, locations = ~code, marker = list(line = l)
  ) %>%
  layout(
    geo = g
  )
```


```{r}
ggplot(aes(x = reorder(Country, diff_f_m), y = diff_f_m, color = diff_valence)) +
  geom_point() +
  geom_hline(yintercept = 0, alpha = 0.75, linetype = 3) +
  scale_color_manual(values = viridis(n = 3, direction = 1, option = "C"), guide = FALSE) +
  scale_x_discrete(expand = expansion(add = 1)) +
  coord_flip()

full_cascade_g %>%
  select(-lower_ci, -upper_ci) %>%
  spread(sex, estimate) %>%
  filter(age == "adult") %>%
  select(-all) %>%
  mutate(diff_f_m = female - male) %>%
  filter(year == "2018", measure_type == "know_status_on_art") %>%
  ggplot(aes(x = reorder(Region, diff_f_m), y = diff_f_m)) +
  geom_point() +
  geom_hline(yintercept = 0, alpha = 0.75, linetype = 3) +
  scale_y_continuous(labels = percent_format(scale = 1)) +
  scale_x_discrete(expand = expansion(add = 1)) +
  coord_flip()

full_cascade_g %>%
  select(-lower_ci, -upper_ci) %>%
  spread(sex, estimate) %>%
  filter(age == "adult") %>%
  select(-all) %>%
  mutate(diff_f_m = female - male) %>%
  filter(year == "2018", measure_type == "on_art_vl_suppress") %>%
  ggplot(aes(x = reorder(Region, diff_f_m), y = diff_f_m)) +
  geom_point() +
  geom_hline(yintercept = 0, alpha = 0.75, linetype = 3) +
  scale_y_continuous(labels = percent_format(scale = 1)) +
  scale_x_discrete(expand = expansion(add = 1)) +
  coord_flip()
```


```{r}
# plots of epidemic transition 1990 to 2018 globally

# plots of global number of people living with HIV
# total population
hiv_ep_g %>%
  filter(measure_type == "hiv_burden", age_group == "All", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  scale_x_discrete(breaks = seq(1990, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Number of people living with HIV all ages, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

ggsave("global_number_living_w_hiv.png", device = "png", width = 6, height = 3, units = "in")

# adults
hiv_ep_g %>%
  filter(measure_type == "hiv_burden", age_group == "Adult (15+)", sex == "all", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Number of adults (ages 15 and above) living with HIV, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# children
hiv_ep_g %>%
  filter(measure_type == "hiv_burden", age_group == "Child (0-14)", sex == "all", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000", linejoin = "mitre", linemitre = 10) +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Number of children (ages 0-14) living with HIV, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")


# plots of global number of AIDS-related deaths
# total population
hiv_ep_g %>%
  filter(measure_type == "deaths", age_group == "All", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  scale_x_discrete(breaks = seq(1990, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Number of annual AIDS-related deaths all ages, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

ggsave("global_aids_deaths.png", device = "png", width = 6, height = 3, units = "in")

# adults
hiv_ep_g %>%
  filter(measure_type == "deaths", age_group == "Adult (15+)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Number of annual AIDS-related deaths among adults (ages 15 and above), 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# children
hiv_ep_g %>%
  filter(measure_type == "deaths", age_group == "Child (0-14)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Number of annual AIDS-related deaths among children (ages 0-14), 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")


# plots of number of people newly infected with HIV globally
# total population
hiv_ep_g %>%
  filter(measure_type == "new_infections", age_group == "All", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Number of people newly infected with HIV, all ages, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# adult
hiv_ep_g %>%
  filter(measure_type == "new_infections", age_group == "Adult", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Number of adults (ages 15-49) newly infected with HIV, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# children
hiv_ep_g %>%
  filter(measure_type == "new_infections", age_group == "Child (0-14)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Number of children (ages 0-14) newly infected with HIV, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")


# plots of incidence rate of HIV globally
# total population
hiv_ep_g %>%
  filter(measure_type == "incidence_rate", age_group == "All", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous() +
  scale_x_discrete(breaks = seq(1990, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "New cases of HIV per 1,000 individuals of all ages, 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

ggsave("global_incidence_rate_hiv.png", device = "png", width = 6, height = 3, units = "in")

# adult
hiv_ep_g %>%
  filter(measure_type == "incidence_rate", age_group == "Adult (15-49)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  labs(x = NULL, y = NULL, 
       title = "Incidence rate of HIV among adults (ages 15-49), 1990-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")
```


```{r}
# plots of ART coverage 1990 to 2018 globally

# plots of global proportion of people living with HIV on ART
# total population
hiv_tx_g %>%
  filter(measure_type == "hiv_on_art", age_group == "All", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = percent_format(scale = 1)) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Percent of people living with HIV receiving ART, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# adults
hiv_tx_g %>%
  filter(measure_type == "hiv_on_art", age_group == "Adult (15+)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = percent_format(scale = 1)) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Percent of adults (ages 15 and above) living with HIV receiving ART, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# children
hiv_tx_g %>%
  filter(measure_type == "hiv_on_art", age_group == "Child (0-14)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = percent_format(scale = 1)) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Percent of children (ages 0-14) living with HIV receiving ART, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")


# plots of global numbers of people living with HIV on ART
# total population
hiv_tx_g %>%
  filter(measure_type == "number_on_art", age_group == "All", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Number of people living with HIV receiving ART, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# adult
hiv_tx_g %>%
  filter(measure_type == "number_on_art", age_group == "Adult (15+)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Number of adults (ages 15 and above) living with HIV receiving ART, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# children
hiv_tx_g %>%
  filter(measure_type == "number_on_art", age_group == "Child (0-14)", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Number of children (ages 0-14) living with HIV receiving ART, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# number pregnant women receiving PMTCT
hiv_tx_g %>%
  filter(measure_type == "number_on_pmtct", age_group == "Pregnant", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = comma_format()) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Number of mothers receiving an effective PMTCT regimen, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")

# number pregnant women receiving PMTCT
hiv_tx_g %>%
  filter(measure_type == "pmtct_coverage", age_group == "Pregnant", region == "Global") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.3, fill = "#000000") + 
  geom_line(color = "#000000") +
  scale_y_continuous(labels = percent_format(scale = 1),
                     expand = expansion(add = 10)) +
  scale_x_discrete(breaks = seq(2010, 2018, by = 2)) +
  labs(x = NULL, y = NULL, 
       title = "Percent of mothers receiving an effective PMTCT regimen, 2010-2018",
       subtitle = "Figure based on modeled estimates from UNAIDS",
       caption = "Source: UNAIDS 2019 estimates")
```



```{r}
# plots of epidemic transition 1990 to 2018 by region

# plots of number of people living with HIV by region
# total population
hiv_ep_g %>%
  filter(measure_type == "hiv_burden", age_group == "All") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Total number of people living with HIV by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# adults
hiv_ep_g %>%
  filter(measure_type == "hiv_burden", age_group == "Adult (15+)", sex == "all") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Number of adults (ages 15 and above) living with HIV by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# children
hiv_ep_g %>%
  filter(measure_type == "hiv_burden", age_group == "Child (0-14)") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Number of children (ages 0-14) living with HIV by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")


# plots of number of AIDS-related deaths by region
# total population
hiv_ep_g %>%
  filter(measure_type == "deaths", age_group == "All") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Total number of annual AIDS-related deaths by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# adults
hiv_ep_g %>%
  filter(measure_type == "deaths", age_group == "Adult (15+)") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Number of annual AIDS-related deaths among adults (ages 15 and above) by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# children
hiv_ep_g %>%
  filter(measure_type == "deaths", age_group == "Child (0-14)") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Number of annual AIDS-related deaths among children (ages 0-14) by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")


# plots of number of people newly infected with HIV by region
# total population
hiv_ep_g %>%
  filter(measure_type == "new_infections", age_group == "All") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Total number of people newly infected with HIV by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# adult
hiv_ep_g %>%
  filter(measure_type == "new_infections", age_group == "Adult") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Total number of adults (ages 15-49) newly infected with HIV by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# children
hiv_ep_g %>%
  filter(measure_type == "new_infections", age_group == "Child (0-14)") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Total number of children (ages 0-14) newly infected with HIV by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# plots of incidence rate of HIV by region
# total population
hiv_ep_g %>%
  filter(measure_type == "incidence_rate", age_group == "All") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Incidence rate of HIV by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")

# adult
hiv_ep_g %>%
  filter(measure_type == "incidence_rate", age_group == "Adult (15-49)") %>%
  ggplot(aes(x = year, y = estimate, group = region)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, fill = region), alpha = 0.3) + 
  geom_line(aes(color = region)) +
  facet_wrap(~ region) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  labs(x = NULL, y = NULL, 
       title = "Incidence rate of HIV among adults (ages 15-49) by region",
       subtitle = "Figure based on modeled estimates from UNAIDS for all ages",
       caption = "Source: UNAIDS special analysis, 2019")
```


```{r}
# percent change over time
percent_change_g <- hiv_ep_g %>%
    filter(year %in% c("2013", "2018")) %>% 
    select(-lower_ci, -upper_ci) %>% spread(key = year, value = estimate) %>% 
    mutate(percent_change = ((`2018` - `2013`)/`2013`) * 100)

percent_change_c <- hiv_ep_c %>%
    filter(year %in% c("2013", "2018")) %>% 
    select(-lower_ci, -upper_ci) %>% spread(key = year, value = estimate) %>% 
    mutate(percent_change = ((`2018` - `2013`)/`2013`) * 100)

```


```{r}
# maps of percent change 2013 to 2018

# specify light grey boundaries
l <- list(color = toRGB("grey20"), width = 0.5)

# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  landcolor = toRGB("white"),
  showland = TRUE,
  showcountries = TRUE,
  countrycolor = toRGB("grey70"),
  countrywidth = 0.5,
  projection = list(type = 'Mercator')
  )


# plot choropleth of percent change of HIV incidence rate 
percent_change_c %>%
   filter(measure_type == "incidence_rate", age_group == "All") %>%
   plot_geo(offline = TRUE) %>%
   add_trace(
     type = "choropleth", 
     z = ~percent_change, color = ~percent_change, 
     colors = "RdBu", reversescale = TRUE, zmid = 0,
     text = ~country, locations = ~code, marker = list(line = l)
   ) %>%
   layout(
     geo = g
   )
```


