---
title: "HIV Epidemic Status - Data Cleaning"
author: "Brittany Bowman"
date: "9/26/2019"
output: html_document
runtime: shiny
---

This file provides a script for cleaning the HIV 2019 and historical data from UNAIDS related to status of thie HIV epidemic and progress towards ending HIV.

```{r setup, include=FALSE echo = FALSE}
# load necessary packages
library(tidyverse)
library(readxl)

# get working directory
getwd()

# import longitudinal epidemic data
hiv_ep <- read_excel("data/HIV_estimates_from_1990-to-present.xlsx", sheet = 1, skip = 5, na = c("", "NA", "..."))
```


```{r}
# explore dataset
glimpse(hiv_ep)
head(hiv_ep)
```

Create subsets of the dataset.

```{r}
# find column names
column_names <- colnames(hiv_ep)
column_names

# select adult HIV prevalence columns
hiv_prev_adult <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Adult (15-49) prevalence (%)",
         lower_ci = "Adult (15-49) prevalence (%) - LOW ESTIMATE",
         upper_ci = "Adult (15-49) prevalence (%) - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Adult (15-49)",
         sex = "all",
         measure_type = "prevalence") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select young women HIV prevalence columns
hiv_prev_yw <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Young women (15-24) prevalence (%)",
         lower_ci = "Young women (15-24) prevalence (%) - LOW ESTIMATE",
         upper_ci = "Young women (15-24) prevalence (%) - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Young adult (15-24)",
         sex = "female",
         measure_type = "prevalence") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select young men HIV prevalence columns
hiv_prev_ym <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Young men (15-24) prevalence (%)",
         lower_ci = "Young men (15-24) prevalence (%) - LOW ESTIMATE",
         upper_ci = "Young men (15-24) prevalence (%) - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Young adult (15-24)",
         sex = "male",
         measure_type = "prevalence") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select total AIDS-related deaths columns
aids_deaths_total <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "AIDS-related deaths in adults and children",
         lower_ci = "AIDS-related deaths in adults and children - LOW ESTIMATE",
         upper_ci = "AIDS-related deaths in adults and children - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "All",
         sex = "all",
         measure_type = "deaths") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select children AIDS-related deaths columns
aids_deaths_children <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "AIDS-related deaths in children(0-14)",
         lower_ci = "AIDS-related deaths in children(0-14) - LOW ESTIMATE",
         upper_ci = "AIDS-related deaths in children(0-14) - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Child (0-14)",
         sex = "all",
         measure_type = "deaths") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select adults AIDS-related deaths columns
aids_deaths_adult <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "AIDS-related deaths in adults (15+)",
         lower_ci = "AIDS-related deaths in adults (15+) - LOW ESTIMATE",
         upper_ci = "AIDS-related deaths in adults (15+) - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Adult (15+)",
         sex = "all",
         measure_type = "deaths") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select children living with HIV columns
hiv_burden_children <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Estimated children (0-14) living with HIV",
         lower_ci = "Estimated children (0-14) living with HIV - LOW ESTIMATE",
         upper_ci = "Estimated children (0-14) living with HIV - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Child (0-14)",
         sex = "all",
         measure_type = "hiv_burden") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select adult women living with HIV columns
hiv_burden_adult_w <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Estimated women (15+) living with HIV",
         lower_ci = "Estimated women (15+) living with HIV - LOW ESTIMATE",
         upper_ci = "Estimated women (15+) living with HIV - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Adult (15+)",
         sex = "female",
         measure_type = "hiv_burden") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select adults living with HIV columns
hiv_burden_adult <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Estimated adults (15+) living with HIV",
         lower_ci = "Estimated adults (15+) living with HIV - LOW ESTIMATE",
         upper_ci = "Estimated adults (15+) living with HIV - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Adult (15+)",
         sex = "all",
         measure_type = "hiv_burden") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select total people living with HIV columns
hiv_burden_total <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Estimated adults and children living with HIV",
         lower_ci = "Estimated adults and children living with HIV - LOW ESTIMATE",
         upper_ci = "Estimated adults and children living with HIV - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "All",
         sex = "all",
         measure_type = "hiv_burden") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select adult HIV incident rate columns
hiv_incident_rate_adult <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Adult (15-49) incidence rate (per 100)",
         lower_ci = "Adult (15-49) incidence rate (per 100) - LOW ESTIMATE",
         upper_ci = "Adult (15-49) incidence rate (per 100) - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Adult (15-49)",
         sex = "all",
         measure_type = "incidence_rate") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select total HIV incident rate columns
hiv_incident_rate_total <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "All ages incidence rate (per 1000)",
         lower_ci = "All ages incidence rate (per 1000) - LOW ESTIMATE",
         upper_ci = "All ages incidence rate (per 1000) - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "All",
         sex = "all",
         measure_type = "incidence_rate") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select pregnant women needsing ART to prevent PMTCT columns
hiv_pregnant_need_art <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Mothers Needing Antiretrovirals For Preventing Mother-to-Child Transmission",
         lower_ci = "Mothers Needing Antiretrovirals For Preventing Mother-to-Child Transmission - LOW ESTIMATE",
         upper_ci = "Mothers Needing Antiretrovirals For Preventing Mother-to-Child Transmission - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Pregnant",
         sex = "female",
         measure_type = "pregnant_need_art") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select new HIV infections children columns
hiv_new_infections_children <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Children (0-14) newly infected with HIV",
         lower_ci = "Children (0-14)  newly infected with HIV - LOW ESTIMATE",
         upper_ci = "Children (0-14)  newly infected with HIV - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Child (0-14)",
         sex = "all",
         measure_type = "new_infections") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select new HIV infections adults columns
hiv_new_infections_adult <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Adults newly infected with HIV",
         lower_ci = "Adults newly infected with HIV - LOW ESTIMATE",
         upper_ci = "Adults newly infected with HIV - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "Adult",
         sex = "all",
         measure_type = "new_infections") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)

# select new HIV infections adults columns
hiv_new_infections_total <- hiv_ep %>% 
  select(year = "...1",
         code = "...2",
         region = "...3",
         estimate = "Adults and children newly infected with HIV" ,
         lower_ci = "Adults and children newly infected with HIV - LOW ESTIMATE",
         upper_ci = "Adults and children newly infected with HIV - HIGH ESTIMATE"
         ) %>%
  mutate(age_group = "All",
         sex = "all",
         measure_type = "new_infections") %>%
  select(code, region, year, measure_type, estimate, lower_ci, upper_ci, age_group, sex)
```

Bind subsets into reformatted master dataset and tidy.

```{r}
# bind datasets together
tidy_hiv_ep <- bind_rows(hiv_prev_adult, hiv_prev_yw, hiv_prev_ym, aids_deaths_total, aids_deaths_children, aids_deaths_adult,
                         hiv_burden_children, hiv_burden_adult_w, hiv_burden_adult, hiv_burden_total, hiv_incident_rate_adult,
                         hiv_incident_rate_total, hiv_pregnant_need_art, hiv_new_infections_children, hiv_new_infections_adult,
                         hiv_new_infections_total)

glimpse(tidy_hiv_ep)

# remove any "<" or ">" characters (just set to value)
tidy_hiv_ep <- tidy_hiv_ep %>%
  map(str_replace_all, "<", "") %>%
  map(str_replace_all, ">", "") %>%
  as_tibble()

# remove any spaces from estimate, lower_ci, and upper_ci columns so they can be converted to numbers
tidy_hiv_ep <- tidy_hiv_ep %>%
  mutate(estimate = str_replace_all(estimate," ", "")) %>%
  mutate(lower_ci = str_replace_all(lower_ci," ", "")) %>%
  mutate(upper_ci = str_replace_all(upper_ci," ", "")) %>%
  as_tibble()

# trim white space from region column
tidy_hiv_ep <- tidy_hiv_ep %>%
  mutate(region = str_trim(region, side = "both")) %>%
  mutate(region = str_remove_all(region, pattern = "   ")) %>%
  as_tibble()

# convert column types
tidy_hiv_ep <- tidy_hiv_ep %>%
  mutate(year = factor(year),
         estimate = as.numeric(estimate),
         lower_ci = as.numeric(lower_ci),
         upper_ci = as.numeric(upper_ci))

glimpse(tidy_hiv_ep)

# split into global/regional dataset and country dataset
tidy_hiv_ep_g <- tidy_hiv_ep %>%
  filter(is.na(code)) %>%
  select(-code)

tidy_hiv_ep_c <- tidy_hiv_ep %>%
  filter(!is.na(code)) %>%
  rename(country = region)
```




